[package]
name = "pi_adapter_slack"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pi_contracts = { path = "../../contracts" }
pi_core = { path = "../../core" }
